// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGYLn0Jqy7Gw3SePfIJXUEadIre8_SK4M',
    appId: '1:229532377412:web:6d8f17045a3218b0103711',
    messagingSenderId: '229532377412',
    projectId: 'proyecto-ea-auth',
    authDomain: 'proyecto-ea-auth.firebaseapp.com',
    storageBucket: 'proyecto-ea-auth.appspot.com',
    measurementId: 'G-CQ743Q35VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhyj5m94A_2LHMu75IMsr4iU8VMr3OU0Y',
    appId: '1:229532377412:android:04d8bced162aa733103711',
    messagingSenderId: '229532377412',
    projectId: 'proyecto-ea-auth',
    storageBucket: 'proyecto-ea-auth.appspot.com',
  );
}